// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA50zS33aKW9lMJ2Wv8V8Hc09rOAN6pZdw',
    appId: '1:477251828061:web:02288e5c86e1ad293950b4',
    messagingSenderId: '477251828061',
    projectId: 'movies-21ec5',
    authDomain: 'movies-21ec5.firebaseapp.com',
    storageBucket: 'movies-21ec5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADyElgVUuAueZV4lxHltvUzwzSHe4JWUo',
    appId: '1:477251828061:android:ab68410a239b112a3950b4',
    messagingSenderId: '477251828061',
    projectId: 'movies-21ec5',
    storageBucket: 'movies-21ec5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATV7eT7WvOqg0eowMv8pNM2EjqwUaVgaU',
    appId: '1:477251828061:ios:928edacfed5a18453950b4',
    messagingSenderId: '477251828061',
    projectId: 'movies-21ec5',
    storageBucket: 'movies-21ec5.appspot.com',
    iosClientId: '477251828061-qt10uj1uq7230v3vas22dqdef752vnbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATV7eT7WvOqg0eowMv8pNM2EjqwUaVgaU',
    appId: '1:477251828061:ios:7e10d65f4870eed23950b4',
    messagingSenderId: '477251828061',
    projectId: 'movies-21ec5',
    storageBucket: 'movies-21ec5.appspot.com',
    iosClientId: '477251828061-68roh19kbpr5bfsn263bf528buialrv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies.RunnerTests',
  );
}
